### ISSUE TITLE
Modelado del Problema

### ISSUE THREAD

**Issue by KleoMaple** [KleoMaple/Aguayo-Tech#2]
1. Deben modelar el problema como un grafo, donde el almacén y las ubicaciones de los clientes se representan como nodos y las distancias entre ellos como aristas.
2. Definir las restricciones, como los límites de capacidad de los vehículos y cualquier requisito específico para cada punto de entrega.

**Comment by EmilianoAnaya** [comment]
![Image](https://github.com/KleoMaple/Aguayo-Tech/assets/150195114/da372da8-3fc0-4d75-86f1-93f6fd509c6e)
![Image](https://github.com/KleoMaple/Aguayo-Tech/assets/150195114/d259e58c-8bbd-4b32-a202-c8df4ce27443)

**Comment by KleoMaple** [comment]
![Image](https://github.com/KleoMaple/Aguayo-Tech/assets/88137469/7a220e8d-6a99-4e3f-83ad-afe119fdf841)

**Comment by EmilianoAnaya** [comment]
Diagrama de Flujo Proyecto:

![Diagrama_flujo_Proyecto](https://github.com/KleoMaple/Aguayo-Tech/assets/150195114/2e7ff415-39ea-427d-b836-d61c00f15964)

**Comment by NayleaDanae** [comment]
Boceto de la interfaz

[BocetoAguayoTech.pdf](https://github.com/KleoMaple/Aguayo-Tech/files/13482100/BocetoAguayoTech.pdf)


Diagrama caso de uso

[DiagramaCasoUso.pdf](https://github.com/KleoMaple/Aguayo-Tech/files/13482102/DiagramaCasoUso.pdf)
