### ISSUE TITLE
Generación de Datos de Entrada

### ISSUE THREAD

**Issue by KleoMaple** [KleoMaple/Aguayo-Tech#3]
Cada equipo debe crear un conjunto de datos de entrada para el problema. Esto
incluye especificar las coordenadas del almacén (depósito), las ubicaciones de los
clientes y la capacidad de cada vehículo. Los datos deben ser presentados en un
formato estructurado.

**Comment by NahomiLunaOR** [comment]
[D01_Proyecto_Aguayo_Tech_Conjunto_De_Datos.pdf](https://github.com/KleoMaple/Aguayo-Tech/files/13480998/D01_Proyecto_Aguayo_Tech_Conjunto_De_Datos.pdf)
