### ISSUE TITLE
Selección de Algoritmo

### ISSUE THREAD

**Issue by KleoMaple** [KleoMaple/Aguayo-Tech#4]
Cada equipo debe elegir un algoritmo (o una combinación de algoritmos) para
resolver el problema de optimización. Pueden considerar:

- El Problema del Viajante de Comercio (TSP) para encontrar la ruta más corta que visite a todos los clientes exactamente una vez.

- El Problema de Enrutamiento de Vehículos (VRP) para optimizar las rutas teniendo en cuenta la capacidad de los vehículos y las restricciones.

- Algoritmos metaheurísticos como algoritmos genéticos, recocido simulado u optimización por colonias de hormigas para soluciones más complejas.

**Comment by EmilianoAnaya** [comment]
- Librería de Interfaz Gráfica: Tkinter

**Comment by EmilianoAnaya** [comment]
Selección de Interfaz para código:

[Tecnologías en la Implementación de Interfaz.pdf](https://github.com/KleoMaple/Aguayo-Tech/files/13481429/Tecnologias.en.la.Implementacion.de.Interfaz.pdf)

**Comment by CarlosAvilaDev** [comment]
[seleccion del algoritmo.pdf](https://github.com/KleoMaple/Aguayo-Tech/files/13481509/seleccion.del.algoritmo.pdf)
