### ISSUE TITLE
Implementación

### ISSUE THREAD

**Issue by KleoMaple** [KleoMaple/Aguayo-Tech#5]
Implementar el algoritmo seleccionado en Python.

**Comment by CarlosAvilaDev** [comment]
![Image](https://github.com/KleoMaple/Aguayo-Tech/assets/117247813/fcbec17b-459d-436e-8d4a-44c7ca5e9ad3)



![Image](https://github.com/KleoMaple/Aguayo-Tech/assets/117247813/dee2294a-6d9d-413e-b100-00725afeebfa)



![Image](https://github.com/KleoMaple/Aguayo-Tech/assets/117247813/51df9b53-8da5-4ff8-85c8-e8c9e033f9a5)



![Image](https://github.com/KleoMaple/Aguayo-Tech/assets/117247813/dc560488-953e-4999-ba10-54434244b0f2)



![Image](https://github.com/KleoMaple/Aguayo-Tech/assets/117247813/f6329b0a-500e-4d7e-8d25-30b2dd54b867)



![Image](https://github.com/KleoMaple/Aguayo-Tech/assets/117247813/3919a751-f888-4c8a-84cd-59228085d07d)
