### ISSUE TITLE
Interfaz de Usuario

### ISSUE THREAD

**Issue by KleoMaple** [KleoMaple/Aguayo-Tech#6]
Desarrollar una interfaz de usuario amigable que permita a los usuarios cargar los
datos de entrada, visualizar las rutas optimizadas y obtener las soluciones.

**Comment by EmilianoAnaya** [comment]
Capturas de Interfaz de Usuario

![Captura de pantalla 2023-11-27 165521](https://github.com/KleoMaple/Aguayo-Tech/assets/150195114/92baeb81-4cf3-477b-affe-2194878a9678)
![Captura de pantalla 2023-11-27 165528](https://github.com/KleoMaple/Aguayo-Tech/assets/150195114/fc1faa67-f7fa-4366-9217-4fce52cdccf5)
![Captura de pantalla 2023-11-27 165536](https://github.com/KleoMaple/Aguayo-Tech/assets/150195114/006f5c14-4b36-4761-bddc-d2b66fd4d95d)
![Captura de pantalla 2023-11-27 165600](https://github.com/KleoMaple/Aguayo-Tech/assets/150195114/b7abe84a-f326-4f55-880f-52849f669e8e)
