### ISSUE TITLE
Estrategias de Optimización

### ISSUE THREAD

**Issue by KleoMaple** [KleoMaple/Aguayo-Tech#7]
Implementar estrategias de optimización para mejorar las rutas generadas por el
algoritmo. Asegurarse de que las entregas cumplan con las restricciones de
capacidad de los vehículos.

**Comment by NahomiLunaOR** [comment]
[D01_Proyecto_Aguayo_Tech_TestPlan.pdf](https://github.com/KleoMaple/Aguayo-Tech/files/13481111/D01_Proyecto_Aguayo_Tech_TestPlan.pdf)
