### ISSUE TITLE
Pruebas y Validación

### ISSUE THREAD

**Issue by KleoMaple** [KleoMaple/Aguayo-Tech#8]
- Probar el algoritmo con diferentes conjuntos de datos, incluyendo instancias pequeñas y grandes.

- Verificar que el algoritmo produzca soluciones válidas y óptimas o cercanas a las óptimas. Comparar los resultados con soluciones de referencia (si están disponibles).

**Comment by NahomiLunaOR** [comment]
[D01_Proyecto_Aguayo_Tech_Preubas.pdf](https://github.com/KleoMaple/Aguayo-Tech/files/13481007/D01_Proyecto_Aguayo_Tech_Preubas.pdf)
