### ISSUE TITLE
Implementación de la optimización

### ISSUE THREAD

**Issue by KleoMaple** [KleoMaple/Aguayo-Tech#9]
Se implementará las estrategias de optimización dadas y cualquier mejora posible

**Comment by NahomiLunaOR** [comment]
![Image](https://github.com/KleoMaple/Aguayo-Tech/assets/150195611/133affaf-b8d8-41f0-b7cc-92250f36bc39)

**Comment by CarlosAvilaDev** [comment]
[documentacion_backend.pdf](https://github.com/KleoMaple/Aguayo-Tech/files/13481483/documentacion_backend.pdf)
